import type { ModelOption } from './types';
import modelDescriptions from './modelDescriptions';

export const mobilenetModels: ModelOption[] = [
  {
    name: "MobileNetV1",
    submodels: {
      default: {
        filename: "mobilenetv1.pth",
        parameters: 4_231_976,
        layers: 28,
        flops: "0.57 GFLOPS",
        mAP: "70.6%",
        inputSize: "224x224",
        speed: "1.8ms",
        memoryUsage: "16 MB",
        description: "Depthwise separable convolutions for mobile deployment",
      },
    },
    image: "https://machinethink.net/images/mobilenet-v2/ResidualBlock@2x.png",
    description: modelDescriptions.MobileNetV1,
    backbone: "MobileNetV1",
    neck: "None",
    head: "Global Average Pooling + FC",
    releaseYear: 2017,
    framework: "TensorFlow",
  },
  {
    name: "MobileNetV2",
    submodels: {
      default: {
        filename: "mobilenetv2.pth",
        parameters: 3_504_872,
        layers: 53,
        flops: "0.3 GFLOPS",
        mAP: "72.0%",
        inputSize: "224x224",
        speed: "1.5ms",
        memoryUsage: "13 MB",
        description: "Inverted residuals with linear bottlenecks for efficiency",
      },
    },
    image: "https://machinethink.net/images/mobilenet-v2/ResidualBlock@2x.png",
    description: modelDescriptions.MobileNetV2,
    backbone: "MobileNetV2",
    neck: "None",
    head: "Global Average Pooling + FC",
    releaseYear: 2018,
    framework: "TensorFlow",
  },
  {
    name: "MobileNetV3",
    submodels: {
      Small: {
        filename: "mobilenetv3-small.pth",
        parameters: 2_542_856,
        layers: 30,
        flops: "0.06 GFLOPS",
        mAP: "67.4%",
        inputSize: "224x224",
        speed: "0.9ms",
        memoryUsage: "10 MB",
        description: "Compact model for resource-constrained edge devices",
      },
      Large: {
        filename: "mobilenetv3-large.pth",
        parameters: 5_483_032,
        layers: 30,
        flops: "0.22 GFLOPS",
        mAP: "75.2%",
        inputSize: "224x224",
        speed: "1.4ms",
        memoryUsage: "21 MB",
        description: "Enhanced model with squeeze-and-excitation blocks and h-swish",
      },
    },
    image: "https://machinethink.net/images/mobilenet-v2/ResidualBlock@2x.png",
    description: modelDescriptions.MobileNetV3,
    backbone: "MobileNetV3",
    neck: "SE Blocks",
    head: "Global Average Pooling + FC",
    releaseYear: 2019,
    framework: "PyTorch",
  },
];
