import type { ModelOption } from './types';
import modelDescriptions from './modelDescriptions';

export const resnetModels: ModelOption[] = [
  {
    name: "ResNet18",
    submodels: {
      default: {
        filename: "resnet18.pth",
        parameters: 11_689_512,
        layers: 18,
        flops: "1.8 GFLOPS",
        mAP: "69.8%",
        inputSize: "224x224",
        speed: "3.1ms",
        memoryUsage: "45 MB",
        description: "Lightweight residual network for image classification",
      },
    },
    image: "https://miro.medium.com/v2/resize:fit:1400/1*Y-u7dH42oZSs8g3yLyZzJA.png",
    description: modelDescriptions.ResNet18,
    backbone: "ResNet18",
    neck: "None",
    head: "Global Average Pooling + FC",
    releaseYear: 2015,
    framework: "PyTorch",
  },
  {
    name: "ResNet34",
    submodels: {
      default: {
        filename: "resnet34.pth",
        parameters: 21_797_672,
        layers: 34,
        flops: "3.7 GFLOPS",
        mAP: "73.3%",
        inputSize: "224x224",
        speed: "4.7ms",
        memoryUsage: "83 MB",
        description: "Deeper residual network with improved feature learning",
      },
    },
    image: "https://miro.medium.com/v2/resize:fit:1400/1*Y-u7dH42oZSs8g3yLyZzJA.png",
    description: modelDescriptions.ResNet34,
    backbone: "ResNet34",
    neck: "None",
    head: "Global Average Pooling + FC",
    releaseYear: 2015,
    framework: "PyTorch",
  },
  {
    name: "ResNet50",
    submodels: {
      default: {
        filename: "resnet50.pth",
        parameters: 25_557_032,
        layers: 50,
        flops: "4.1 GFLOPS",
        mAP: "76.1%",
        inputSize: "224x224",
        speed: "6.2ms",
        memoryUsage: "98 MB",
        description: "Standard ResNet with bottleneck architecture for production use",
      },
    },
    image: "https://miro.medium.com/v2/resize:fit:1400/1*Y-u7dH42oZSs8g3yLyZzJA.png",
    description: modelDescriptions.ResNet50,
    backbone: "ResNet50",
    neck: "None",
    head: "Global Average Pooling + FC",
    releaseYear: 2015,
    framework: "PyTorch",
  },
  {
    name: "ResNet101",
    submodels: {
      default: {
        filename: "resnet101.pth",
        parameters: 44_549_160,
        layers: 101,
        flops: "7.8 GFLOPS",
        mAP: "77.4%",
        inputSize: "224x224",
        speed: "9.8ms",
        memoryUsage: "170 MB",
        description: "Deep residual network for demanding classification tasks",
      },
    },
    image: "https://miro.medium.com/v2/resize:fit:1400/1*Y-u7dH42oZSs8g3yLyZzJA.png",
    description: modelDescriptions.ResNet101,
    backbone: "ResNet101",
    neck: "None",
    head: "Global Average Pooling + FC",
    releaseYear: 2015,
    framework: "PyTorch",
  },
  {
    name: "ResNet152",
    submodels: {
      default: {
        filename: "resnet152.pth",
        parameters: 60_192_808,
        layers: 152,
        flops: "11.6 GFLOPS",
        mAP: "78.3%",
        inputSize: "224x224",
        speed: "14.2ms",
        memoryUsage: "230 MB",
        description: "Maximum depth ResNet for highest classification accuracy",
      },
    },
    image: "https://miro.medium.com/v2/resize:fit:1400/1*Y-u7dH42oZSs8g3yLyZzJA.png",
    description: modelDescriptions.ResNet152,
    backbone: "ResNet152",
    neck: "None",
    head: "Global Average Pooling + FC",
    releaseYear: 2015,
    framework: "PyTorch",
  },
];
