import type { ModelOption } from './types';
import modelDescriptions from './modelDescriptions';

export const yoloModels: ModelOption[] = [
  {
    name: "YOLOv3",
    submodels: {
      u: {
        filename: "yolov3u.pt",
        parameters: 8_700_000,
        layers: 24,
        flops: "5.6 GFLOPS",
        mAP: "33.1%",
        inputSize: "416x416",
        speed: "25ms",
        memoryUsage: "33 MB",
        description: "Lightweight version optimized for speed with reduced accuracy",
      },
      Tinyu: {
        filename: "yolov3tinyu.pt",
        parameters: 61_600_000,
        layers: 106,
        flops: "65.2 GFLOPS",
        mAP: "57.9%",
        inputSize: "416x416",
        speed: "51ms",
        memoryUsage: "246 MB",
        description: "Full-size model with high accuracy for general object detection",
      },
      SPPu: {
        filename: "yolov3sppu.pt",
        parameters: 61_600_000,
        layers: 106,
        flops: "65.2 GFLOPS",
        mAP: "57.9%",
        inputSize: "416x416",
        speed: "51ms",
        memoryUsage: "246 MB",
        description: "Full-size model with high accuracy for general object detection",
      },
    },
    image: "https://raw.githubusercontent.com/ultralytics/assets/main/yolov3/banner-yolov3.png",
    description: modelDescriptions.YOLOv3,
    backbone: "Darknet-53",
    neck: "FPN",
    head: "YOLOv3 Head",
    releaseYear: 2018,
    framework: "Darknet",
  },
  {
    name: "YOLOv4",
    submodels: {
      Tiny: {
        filename: "yolov4-tiny.weights",
        parameters: 6_100_000,
        layers: 38,
        flops: "6.9 GFLOPS",
        mAP: "40.2%",
        inputSize: "416x416",
        speed: "22ms",
        memoryUsage: "23 MB",
        description: "Ultra-fast variant for edge devices and real-time applications",
      },
      CSPDarknet53: {
        filename: "yolov4-cspdarknet53.weights",
        parameters: 64_400_000,
        layers: 162,
        flops: "128 GFLOPS",
        mAP: "65.7%",
        inputSize: "512x512",
        speed: "65ms",
        memoryUsage: "256 MB",
        description: "Standard model with CSP backbone for improved gradient flow",
      },
      "Scaled-YOLOv4": {
        filename: "yolov4-scaled-yolov4.weights",
        parameters: 270_000_000,
        layers: 470,
        flops: "447 GFLOPS",
        mAP: "73.1%",
        inputSize: "896x896",
        speed: "180ms",
        memoryUsage: "1 GB",
        description: "Large-scale model for maximum accuracy on high-resolution inputs",
      },
    },
    image: "https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4.png",
    description: modelDescriptions.YOLOv4,
    backbone: "CSPDarknet53",
    neck: "PANet",
    head: "YOLOv4 Head",
    releaseYear: 2020,
    framework: "Darknet",
  },
  {
    name: "YOLOv5",
    submodels: {
      nu: {
        filename: "yolov5nu.pt",
        parameters: 1_900_000,
        layers: 157,
        flops: "4.5 GFLOPS",
        mAP: "28.0%",
        inputSize: "640x640",
        speed: "6.3ms",
        memoryUsage: "3.9 MB",
        description: "Nano model - smallest and fastest, ideal for mobile deployment",
      },
      su: {
        filename: "yolov5su.pt",
        parameters: 7_200_000,
        layers: 157,
        flops: "16.5 GFLOPS",
        mAP: "37.4%",
        inputSize: "640x640",
        speed: "6.4ms",
        memoryUsage: "14 MB",
        description: "Small model - balanced speed and accuracy for edge devices",
      },
      mu: {
        filename: "yolov5mu.pt",
        parameters: 21_200_000,
        layers: 212,
        flops: "49.0 GFLOPS",
        mAP: "45.4%",
        inputSize: "640x640",
        speed: "8.2ms",
        memoryUsage: "40 MB",
        description: "Medium model - good balance for most applications",
      },
      lu: {
        filename: "yolov5lu.pt",
        parameters: 46_500_000,
        layers: 267,
        flops: "109.1 GFLOPS",
        mAP: "49.0%",
        inputSize: "640x640",
        speed: "10.1ms",
        memoryUsage: "89 MB",
        description: "Large model - higher accuracy for production systems",
      },
      xu: {
        filename: "yolov5xu.pt",
        parameters: 86_700_000,
        layers: 322,
        flops: "205.7 GFLOPS",
        mAP: "50.7%",
        inputSize: "640x640",
        speed: "12.1ms",
        memoryUsage: "166 MB",
        description: "Extra-large model - maximum accuracy for demanding applications",
      },
    },
    image: "https://user-images.githubusercontent.com/26833433/136901921-abcfcd9d-f978-4942-9b97-0e3f202907df.png",
    description: modelDescriptions.YOLOv5,
    backbone: "CSPDarknet",
    neck: "SPPF + PANet",
    head: "YOLOv5 Head",
    releaseYear: 2020,
    framework: "PyTorch",
  },
  {
    name: "YOLOv6",
    submodels: {
      Nano: {
        filename: "yolov6-nano.pt",
        parameters: 4_700_000,
        layers: 295,
        flops: "11.4 GFLOPS",
        mAP: "35.0%",
        inputSize: "640x640",
        speed: "2.9ms",
        memoryUsage: "9 MB",
        description: "Highly optimized nano model for industrial deployment",
      },
      Tiny: {
        filename: "yolov6-tiny.pt",
        parameters: 9_700_000,
        layers: 295,
        flops: "24.2 GFLOPS",
        mAP: "41.0%",
        inputSize: "640x640",
        speed: "3.2ms",
        memoryUsage: "18 MB",
        description: "Tiny model with improved efficiency-accuracy tradeoff",
      },
      Small: {
        filename: "yolov6-small.pt",
        parameters: 18_500_000,
        layers: 295,
        flops: "45.3 GFLOPS",
        mAP: "45.0%",
        inputSize: "640x640",
        speed: "4.9ms",
        memoryUsage: "35 MB",
        description: "Small model optimized for edge computing scenarios",
      },
      Medium: {
        filename: "yolov6-medium.pt",
        parameters: 34_900_000,
        layers: 295,
        flops: "85.8 GFLOPS",
        mAP: "50.0%",
        inputSize: "640x640",
        speed: "8.2ms",
        memoryUsage: "66 MB",
        description: "Medium model with enhanced feature extraction",
      },
      Large: {
        filename: "yolov6-large.pt",
        parameters: 59_600_000,
        layers: 295,
        flops: "150.7 GFLOPS",
        mAP: "52.8%",
        inputSize: "640x640",
        speed: "12.3ms",
        memoryUsage: "113 MB",
        description: "Large model for high-accuracy industrial applications",
      },
    },
    image: "https://raw.githubusercontent.com/meituan/YOLOv6/main/assets/speed_comparision_v3.png",
    description: modelDescriptions.YOLOv6,
    backbone: "EfficientRep",
    neck: "RepPAN",
    head: "Efficient Decoupled Head",
    releaseYear: 2022,
    framework: "PyTorch",
  },
  {
    name: "YOLOv7",
    submodels: {
      Tiny: {
        filename: "yolov7-tiny.pt",
        parameters: 6_200_000,
        layers: 200,
        flops: "13.7 GFLOPS",
        mAP: "38.7%",
        inputSize: "640x640",
        speed: "3.1ms",
        memoryUsage: "12 MB",
        description: "Compact model using trainable bag-of-freebies",
      },
      Normal: {
        filename: "yolov7.pt",
        parameters: 37_200_000,
        layers: 314,
        flops: "104.7 GFLOPS",
        mAP: "51.2%",
        inputSize: "640x640",
        speed: "9.1ms",
        memoryUsage: "71 MB",
        description: "Standard model with E-ELAN architecture",
      },
      E6: {
        filename: "yolov7-e6.pt",
        parameters: 97_200_000,
        layers: 468,
        flops: "257.6 GFLOPS",
        mAP: "55.4%",
        inputSize: "1280x1280",
        speed: "28ms",
        memoryUsage: "185 MB",
        description: "Extended model for higher resolution inputs",
      },
      E6E: {
        filename: "yolov7-e6e.pt",
        parameters: 151_700_000,
        layers: 558,
        flops: "421.7 GFLOPS",
        mAP: "56.8%",
        inputSize: "1280x1280",
        speed: "42ms",
        memoryUsage: "289 MB",
        description: "Enhanced E6 with additional depth and capacity",
      },
      W6: {
        filename: "yolov7-w6.pt",
        parameters: 70_400_000,
        layers: 468,
        flops: "180.1 GFLOPS",
        mAP: "54.6%",
        inputSize: "1280x1280",
        speed: "21ms",
        memoryUsage: "134 MB",
        description: "Width-scaled model for high-resolution detection",
      },
      X: {
        filename: "yolov7-x.pt",
        parameters: 71_300_000,
        layers: 468,
        flops: "189.9 GFLOPS",
        mAP: "53.1%",
        inputSize: "640x640",
        speed: "11.4ms",
        memoryUsage: "136 MB",
        description: "Extra-capacity model with extended network width",
      },
    },
    image: "https://raw.githubusercontent.com/WongKinYiu/yolov7/main/figure/performance.png",
    description: modelDescriptions.YOLOv7,
    backbone: "E-ELAN",
    neck: "E-ELAN PANet",
    head: "RepConv Head",
    releaseYear: 2022,
    framework: "PyTorch",
  },
  {
    name: "YOLOv8",
    submodels: {
      n: {
        filename: "yolov8n.pt",
        parameters: 3_200_000,
        layers: 225,
        flops: "8.7 GFLOPS",
        mAP: "37.3%",
        inputSize: "640x640",
        speed: "1.8ms",
        memoryUsage: "6 MB",
        description: "Nano model with anchor-free detection for mobile devices",
      },
      s: {
        filename: "yolov8s.pt",
        parameters: 11_200_000,
        layers: 225,
        flops: "28.6 GFLOPS",
        mAP: "44.9%",
        inputSize: "640x640",
        speed: "2.4ms",
        memoryUsage: "22 MB",
        description: "Small model with improved backbone and neck design",
      },
      m: {
        filename: "yolov8m.pt",
        parameters: 25_900_000,
        layers: 225,
        flops: "78.9 GFLOPS",
        mAP: "50.2%",
        inputSize: "640x640",
        speed: "4.1ms",
        memoryUsage: "52 MB",
        description: "Medium model balancing speed and accuracy",
      },
      l: {
        filename: "yolov8l.pt",
        parameters: 43_700_000,
        layers: 225,
        flops: "165.2 GFLOPS",
        mAP: "52.9%",
        inputSize: "640x640",
        speed: "6.8ms",
        memoryUsage: "83 MB",
        description: "Large model with enhanced feature extraction",
      },
      x: {
        filename: "yolov8x.pt",
        parameters: 68_200_000,
        layers: 225,
        flops: "257.8 GFLOPS",
        mAP: "53.9%",
        inputSize: "640x640",
        speed: "9.7ms",
        memoryUsage: "130 MB",
        description: "Extra-large model for maximum detection performance",
      },
    },
    image: "https://raw.githubusercontent.com/ultralytics/assets/main/yolov8/yolo-comparison-plots.png",
    description: modelDescriptions.YOLOv8,
    backbone: "C2f + SPPF",
    neck: "C2f PANet",
    head: "Decoupled Anchor-Free Head",
    releaseYear: 2023,
    framework: "Ultralytics",
  },
  {
    name: "YOLOv9",
    submodels: {
      n: {
        filename: "yolov9n.pt",
        parameters: 2_000_000,
        layers: 467,
        flops: "7.9 GFLOPS",
        mAP: "39.0%",
        inputSize: "640x640",
        speed: "2.1ms",
        memoryUsage: "4 MB",
        description: "Nano model with PGI (Programmable Gradient Information)",
      },
      s: {
        filename: "yolov9s.pt",
        parameters: 7_100_000,
        layers: 467,
        flops: "26.7 GFLOPS",
        mAP: "46.8%",
        inputSize: "640x640",
        speed: "2.9ms",
        memoryUsage: "14 MB",
        description: "Small model using GELAN (Generalized Efficient Layer Aggregation Network)",
      },
      m: {
        filename: "yolov9m.pt",
        parameters: 20_100_000,
        layers: 604,
        flops: "76.8 GFLOPS",
        mAP: "51.4%",
        inputSize: "640x640",
        speed: "5.2ms",
        memoryUsage: "38 MB",
        description: "Medium model with reversible architecture",
      },
      c: {
        filename: "yolov9c.pt",
        parameters: 25_500_000,
        layers: 604,
        flops: "102.8 GFLOPS",
        mAP: "53.0%",
        inputSize: "640x640",
        speed: "6.1ms",
        memoryUsage: "49 MB",
        description: "Compact model optimized for information bottleneck",
      },
      e: {
        filename: "yolov9e.pt",
        parameters: 58_100_000,
        layers: 740,
        flops: "192.5 GFLOPS",
        mAP: "55.6%",
        inputSize: "640x640",
        speed: "10.5ms",
        memoryUsage: "111 MB",
        description: "Extended model with enhanced gradient flow",
      },
    },
    image: "https://raw.githubusercontent.com/WongKinYiu/yolov9/main/figure/architecture.png",
    description: modelDescriptions.YOLOv9,
    backbone: "GELAN",
    neck: "PGI + PANet",
    head: "Dual Assignment Head",
    releaseYear: 2024,
    framework: "PyTorch",
  },
  {
    name: "YOLOv10",
    submodels: {
      n: {
        filename: "yolov10n.pt",
        parameters: 2_300_000,
        layers: 225,
        flops: "6.7 GFLOPS",
        mAP: "38.5%",
        inputSize: "640x640",
        speed: "1.6ms",
        memoryUsage: "4.5 MB",
        description: "Nano model with NMS-free training for end-to-end detection",
      },
      s: {
        filename: "yolov10s.pt",
        parameters: 7_200_000,
        layers: 225,
        flops: "21.6 GFLOPS",
        mAP: "46.3%",
        inputSize: "640x640",
        speed: "2.0ms",
        memoryUsage: "14 MB",
        description: "Small model using dual label assignment",
      },
      m: {
        filename: "yolov10m.pt",
        parameters: 15_400_000,
        layers: 225,
        flops: "59.1 GFLOPS",
        mAP: "51.1%",
        inputSize: "640x640",
        speed: "3.8ms",
        memoryUsage: "29 MB",
        description: "Medium model with consistent matching metric",
      },
      b: {
        filename: "yolov10b.pt",
        parameters: 19_100_000,
        layers: 225,
        flops: "92.0 GFLOPS",
        mAP: "52.5%",
        inputSize: "640x640",
        speed: "4.9ms",
        memoryUsage: "36 MB",
        description: "Balanced model optimizing latency-accuracy tradeoff",
      },
      l: {
        filename: "yolov10l.pt",
        parameters: 24_400_000,
        layers: 225,
        flops: "120.3 GFLOPS",
        mAP: "53.2%",
        inputSize: "640x640",
        speed: "6.2ms",
        memoryUsage: "46 MB",
        description: "Large model with spatial-channel decoupled downsampling",
      },
      x: {
        filename: "yolov10x.pt",
        parameters: 29_500_000,
        layers: 225,
        flops: "160.4 GFLOPS",
        mAP: "54.4%",
        inputSize: "640x640",
        speed: "8.1ms",
        memoryUsage: "56 MB",
        description: "Extra-large model with rank-guided block design",
      },
    },
    image: "https://raw.githubusercontent.com/THU-MIG/yolov10/main/assets/latency.svg",
    description: modelDescriptions.YOLOv10,
    backbone: "CSPNet with CIB",
    neck: "Spatial-Channel Decoupled PANet",
    head: "NMS-Free Dual Head",
    releaseYear: 2024,
    framework: "Ultralytics",
  },
  {
    name: "YOLOv11",
    submodels: {
      n: {
        filename: "yolov11n.pt",
        parameters: 2_600_000,
        layers: 238,
        flops: "6.5 GFLOPS",
        mAP: "39.5%",
        inputSize: "640x640",
        speed: "1.5ms",
        memoryUsage: "5 MB",
        description: "Latest nano model with improved efficiency and accuracy",
      },
      s: {
        filename: "yolov11s.pt",
        parameters: 9_400_000,
        layers: 238,
        flops: "21.5 GFLOPS",
        mAP: "47.0%",
        inputSize: "640x640",
        speed: "2.1ms",
        memoryUsage: "18 MB",
        description: "Small model with enhanced feature fusion",
      },
      m: {
        filename: "yolov11m.pt",
        parameters: 20_100_000,
        layers: 238,
        flops: "68.0 GFLOPS",
        mAP: "51.5%",
        inputSize: "640x640",
        speed: "4.0ms",
        memoryUsage: "38 MB",
        description: "Medium model with attention mechanisms",
      },
      l: {
        filename: "yolov11l.pt",
        parameters: 25_300_000,
        layers: 238,
        flops: "86.9 GFLOPS",
        mAP: "53.4%",
        inputSize: "640x640",
        speed: "5.1ms",
        memoryUsage: "48 MB",
        description: "Large model optimized for deployment",
      },
      x: {
        filename: "yolov11x.pt",
        parameters: 56_900_000,
        layers: 238,
        flops: "194.9 GFLOPS",
        mAP: "54.7%",
        inputSize: "640x640",
        speed: "9.3ms",
        memoryUsage: "108 MB",
        description: "State-of-the-art model with maximum performance",
      },
    },
    image: "https://raw.githubusercontent.com/ultralytics/assets/main/yolov8/banner-yolov8.png",
    description: modelDescriptions.YOLOv11,
    backbone: "C3k2 + SPPF",
    neck: "C3k2 PANet",
    head: "Enhanced Decoupled Head",
    releaseYear: 2024,
    framework: "Ultralytics",
  },
];
